/*
-- This breaks the views
DROP TABLE INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP;

CREATE TABLE INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(
  MCO                  VARCHAR2(20 BYTE),
  MCOAPP               VARCHAR2(50 BYTE),
  MCO_NAME             VARCHAR2(100 BYTE),
  CONTACT_MGR          VARCHAR2(50 BYTE),
  PERFORMANCE_MGR      VARCHAR2(50 BYTE),
  SHEET_NAME           VARCHAR2(50 BYTE)
);
*/
TRUNCATE TABLE INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP;

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','BMC-BACO','Wellsense Community Alliance','Karen Powell','Caitlin Towey','WLS-BACO');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','BMC-MERCY','Wellsense Mercy Alliance','Karen Powell','Caitlin Towey','WLS-Mercy');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','BMC-SIGN','Wellsense Signature Alliance','Karen Powell','Caitlin Towey','WLS-Signature');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','BMC-SCOAST','Wellsense Southcoast Alliance','Karen Powell','Caitlin Towey','WLS-Southcoast');

-- BMC MCO
INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','WLS','Wellsense Essential - MCO Plan','Karen Powell','Caitlin Towey','WLS');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('FLN','FLN-BERK','Berkshire Fallon Health Collaborative','Kelley Delorey','Chris Barbey','FLN-Berkshire');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('FLN','FLN-REL','Fallon 365 Care','Kelley Delorey','Chris Barbey','FLN-Reliant');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('FLN','FLN-WFC','Fallon Health with Wellforce','Kelley Delorey','Chris Barbey','FLN-Wellforce');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('NHP','NHP-MVA','AllWays Health Partners (formerly Neighborhood Health Plan) with Merrimack Valley ACO','Karen Powell','Tim Sullivan','NHP-MVACO');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('HNE','HNE-BAY','Behealthy Partnership','Kelley Delorey','Tim Sullivan','HNE-Baystate');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('CHA','CHA-ATRIUS','Tufts Health Public Plans with Atrius Health','Ron Reidy','Sarah Patuto','Tufts-Atrius');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('CHA','CHA-BIDCO','Tufts Health Public Plans with Beth Israel Deaconess Care Organization','Ron Reidy','Sarah Patuto','Tufts-BIDCO');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('CHA','CHA-CHA','Tufts Health Together with CHA','Ron Reidy','Sarah Patuto','Tufts-CHA');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('CHA','CHA-CHICO','Tufts Health Public Plans with Boston Children''s Health ACO','Ron Reidy','Sarah Patuto','Tufts-CHICO');

-- Tufts MCO
INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('CHA','THP','Tufts Health Together','Ron Reidy','Sarah Patuto','Tufts-MCO');

-- New ACOs

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','WLS-BCHACO','Wellsense Boston Children''s ACO','Karen Powell','Caitlin Towey','WLS-BCHACO');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','WLS-BILH','Wellsense BILH Performance Network ACO','Karen Powell','Caitlin Towey','WLS-BILH');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','WLS-CARE','Wellsense Care Alliance','Karen Powell','Caitlin Towey','WLS-CARE');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('BMC','WLS-EBNHC','East Boston Neighborhood Health Wellsense Alliance','Karen Powell','Caitlin Towey','WLS-EBNHC');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('CHA','THP-UMMH','Tufts Health Together with UMASS Memorial Health','Ron Reidy','Sarah Patuto','Tufts-UMMH');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('FLN','FLN-ATRIUS','Fallon Health-Atrius Health Care Collaborative','Kelley Delorey','Chris Barbey','FLN-Atrius');

INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('NHP','MGB-MGB','Mass General Brigham Health Plan with Mass General','Karen Powell','Tim Sullivan','MGB-MGB');

-- MBHP MCO
INSERT INTO INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP
(MCO,MCOAPP, MCO_NAME, CONTACT_MGR, PERFORMANCE_MGR, SHEET_NAME)
VALUES
('MBH','MBH','Mass Behavioral Health Partnership','Kathleen Fogg','Jeffrey Neal','MBHP');

COMMIT;

GRANT SELECT ON INF_B_SC_STG_MCO_MBH_MCO_NAME_LOOKUP TO NW_READ;

