--DROP TABLE MCO_MBHP_DOS_FEB2019_MAY2019

CREATE TABLE MCO_MBHP_DOS_FEB2019_MAY2019  
         NOLOGGING 
         COMPRESS 
         AS 
         SELECT 
         ENC.CDE_ENC_MCO, 
         ENC.CDE_ENC_ACO, 
         CASE WHEN ENC.CDE_ENC_ACO in('#','+','-') THEN 'NA' ELSE ENC.CDE_ENC_ACO END AS ACO, 
         MEM.ID_MEDICAID, 
         ENCATT.CDE_ENC_REC_IND, 
         ENCATT.DSC_ENC_REC_IND, 
         ENC.DOS_FROM_DT AS DOS_FROM, 
         ENC.DOS_TO_DT AS DOS_THRU, 
         ENC.REMIT_FROM_DT AS PAID_DT, 
         ENC.ADMIT_DT, 
         ENC.DISCHARGE_DT, 
         ENC.DATE_SCRIPT_WRITTEN, 
         ENC.QTY_REFILL, 
         ENC.QTY_UNITS_BILLED, 
         ENC.RX_NUMBER, 
         ENC.AMT_NDC_PROFEE, 
         ENC.ENCSRGGRP_SEQ, 
         DIAGGRP.CDE_DIAG_ADMIT, 
         DIAGGRP.DSC_DIAG_ADMIT, 
         CSA.CDE_PATIENT_STATUS, 
         CSA.DSC_PATIENT_STATUS, 
         DIAGGRP.CDE_DIAG_1 AS PRIMARY_DIAG, 
         DIAGGRP.DSC_DIAG_1 AS PRIMARY_DIAG_DESC, 
         DIAGGRP.CDE_ICD_VERSION, 
         DIAGGRP.DIAGRP_SEQ, 
         CSA.CDE_ADMIT_TYPE, 
         CSA.DSC_ADMIT_TYPE, 
         CSA.CDE_ADMIT_SOURCE, 
         NCF.CDE_ENC_PROC AS PROC_CODE_ENC, 
         NCF.DSC_ENC_PROC AS PROC_CODE_ENC_DESC, 
         PROC.CDE_PROC AS PROC_CODE, 
         PROC.DSC_PROC AS PROC_CODE_DESC, 
         MFR.CDE_PROC_MOD AS PROC_MODIFIER1,
         MFR.DSC_PROC_MOD AS PROC_MODIFIER1_DESC,
         MFR.CDE_PROC_MOD_2 AS PROC_MODIFIER2,
         MFR.DSC_PROC_MOD_2 AS PROC_MODIFIER2_DESC,
         MFR.CDE_PROC_MOD_3 AS PROC_MODIFIER3,
         MFR.DSC_PROC_MOD_3 AS PROC_MODIFIER3_DESC,
         MFR.CDE_PROC_MOD_4 AS PROC_MODIFIER4,
         MFR.DSC_PROC_MOD_4 AS PROC_MODIFIER4_DESC,
         NCF.CDE_ENC_PROC_TYPE, 
         NCF.DSC_ENC_PROC_TYPE, 
         CSA.CDE_REVENUE, 
         CSA.DSC_REVENUE, 
         CSA.CDE_PLACE_OF_SERVICE, 
         CSA.DSC_PLACE_OF_SERVICE, 
         SUBSTR(CSA.CDE_PLACE_OF_SERVICE,2,2) AS PLACE_OF_SERVICE, 
         SUBSTR(CSA.CDE_PLACE_OF_SERVICE,1,1) AS PLACE_OF_SERVICE_TYPE, 
         CSA.CDE_PLACE_OF_SERVICE_ENC, 
         CSA.CDE_TYPE_OF_BILL, 
         CSA.CDE_TYPE_OF_BILL_ENC, 
         CSA.CDE_BILL_FREQ, 
         SVC_PROV.ID_PROVIDER AS SERV_PROV_ID, 
         SVC_PROV.ENC_PROV_ID AS ENC_SERV_PROV_ID, 
         SVC_PROV.DSC_ENC_PROV_ID_TYPE AS SERV_PROV_ID_TYPE, 
         SVC_PROV.ID_NPI AS SERV_NPI, 
         SVC_PROV.CDE_ENC_PROV_TYPE AS ENC_SERV_PROV_TYPE, 
         SVC_PROV.CDE_ENC_PROV_ID_LOC AS SERV_PROV_ID_LOC_CODE, 
         NCF.CDE_ENC_PROV_SPEC AS SERV_PROV_SPECIALTY,
         PROV.ID_PROVIDER AS BILL_PROV_ID, 
         PROV.ENC_PROV_ID AS ENC_BILL_PROV_ID, 
         PROV.DSC_ENC_PROV_ID_TYPE AS BILL_PROV_ID_TYPE, 
         PROV.CDE_ENC_PROV_ID_LOC AS BILL_PROV_ID_LOC_CODE, 
         PROV.ID_NPI AS BILL_NPI, 
         PRS_PROV.ID_PROVIDER AS PRES_PROV_ID, 
         PRS_PROV.ENC_PROV_ID AS ENC_PRES_PROV_ID, 
         PRS_PROV.DSC_ENC_PROV_ID_TYPE AS PRES_PROV_ID_TYPE, 
         PRS_PROV.CDE_ENC_PROV_ID_LOC AS PRS_PROV_ID_LOC_CODE, 
         DRG.CDE_DRUG_CLASS, 
         DRG.CDE_NDC, 
         ENC.CDE_CLM_TYPE AS CLAIM_TYPE, 
         ENC.ENC_CLAIM_NO, 
         ENC.ENC_CLAIM_SUFFIX, 
         ENC.AMT_PAID, 
         ENC.AMT_BILLED, 
         ENC.AMT_ALLOWED, 
         ENC.CDE_CLM_DISPOSITION, 
         ENC.AMT_TPL, 
         ENC.AMT_COPAY, 
         ENC.AMT_COINSURANCE, 
         ENC.NUM_LOGICAL_CLAIM, 
         ENCATT.CDE_ENC_DISP_AS_WRTN, 
         ENCATT.DSC_ENC_DISP_AS_WRTN, 
         ENCATT.CDE_ENC_CLAIM_CAT, 
         ENCATT.DSC_ENC_CLAIM_CAT, 
         ENCATT.CDE_ENC_SVC_CAT, 
         ENCATT.DSC_ENC_SVC_CAT, 
         ENCATT.IND_ENC_COMPOUND 
         FROM NW_ENCOUNTER_HIST ENC 
         LEFT OUTER JOIN NW.NW_ENC_ATTRIBUTE ENCATT ON ENC.ATTRENC_SEQ = ENCATT.ATTRENC_SEQ 
         LEFT OUTER JOIN NW_MEMBER MEM ON ENC.MEM_SEQ = MEM.MEM_SEQ 
         LEFT OUTER JOIN NW_DIAGNOSIS_GROUP DIAGGRP ON ENC.DIAGRP_SEQ = DIAGGRP.DIAGRP_SEQ 
         LEFT OUTER JOIN NW_CLAIM_SERVICE_ATTRIBUTE CSA ON ENC.ATTRSRV_SEQ = CSA.ATTRSRV_SEQ 
         LEFT OUTER JOIN NW_PROCEDURE PROC ON ENC.PROC_SEQ = PROC.PROC_SEQ 
         LEFT OUTER JOIN NW_PROCEDURE_MFR_GROUP MFR ON ENC.PROCMFRGRP_SEQ= MFR.PROCMFRGRP_SEQ 
         LEFT OUTER JOIN NW_DRUG DRG ON ENC.DRUG_SEQ = DRG.DRUG_SEQ 
         LEFT OUTER JOIN NW_ENC_PROVIDER PROV ON ENC.BILL_ENCPRV_SEQ = PROV.ENCPRV_SEQ 
         LEFT OUTER JOIN NW_ENC_PROVIDER SVC_PROV ON ENC.SRV_ENCPRV_SEQ = SVC_PROV.ENCPRV_SEQ 
         LEFT OUTER JOIN NW_ENC_PROVIDER REF_PROV ON ENC.REF_ENCPRV_SEQ = REF_PROV.ENCPRV_SEQ 
         LEFT OUTER JOIN NW_ENC_PROVIDER PRS_PROV ON ENC.PRS_ENCPRV_SEQ = PRS_PROV.ENCPRV_SEQ 
         LEFT OUTER JOIN NW_ENC_NONCONF_ATTRIBUTE NCF ON NCF.ATTRENC_NC_SEQ = ENC.ATTRENC_NC_SEQ 
 
         WHERE  ENC.DOS_FROM_DT BETWEEN TO_DATE('20190201','YYYYMMDD') 
                 AND ((TO_DATE('20190201', 'YYYYMMDD') + INTERVAL '4' MONTH ) -1)
         AND  ENC.REMIT_THRU_DT = TO_DATE('99991231','YYYYMMDD')   
         AND TO_DATE('20191105','YYYYMMDD') BETWEEN ENC.WH_FROM_DT AND ENC.WH_THRU_DT   
         AND ENC.CDE_CLM_DISPOSITION <> 'V' 
         AND ENC.IND_OFFSET = 'N' 
         AND ENC.CDE_ENC_MCO IN('BMC','CHA','FLN','NHP','HNE','MBH')  
