	/*THIS PROGRAM CREATES THE ADDITIONAL DOS DATA WHICH IS USED TO REPORT ON THE DATA COMPLETENESS*/
/* User needs to modify time prompts (n=4) ex 12mos 3mos 1month*/
    
%GLOBAL UID PWRD FLDR YEARSTRT MONSTRT QUARTER DTRNG DELX OBSCOUNT DSETS REVDATE MISSX NUMREXX  OBREX MONYY TIMETITLE; 

    %window compo IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = WHITE

            #08 @10 'THIS JOB WILL CREATE THE QUARTERLY MCO/MBHP COMPLETENESS REPORTS COVERING 12 MONTH DOS PERIOD' 
						ATTR = UNDERLINE C = GREEN
		#14 @10 'PLEASE ENTER YOUR ORACLE ID HERE: ' attr = underline C = BLUE
                 			+4 UID 20 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
		#16 @25 'AND YOUR ORACLE PASSWORD HERE: ' ATTR = UNDERLINE C = BLUE
                 			+4  PWRD 30 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
		#18 '---------------------------------------------------------------------------------------------------------------------------'
		#20 @10 'ENTER THE START MONTH FOR THE DATA EXTRACT, (IN THREE LETTERS E.G. MAY): ' 
						ATTR = UNDERLINE C = BLUE 
				+ 2 MONSTRT ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
            #22 @10 'ENTER THE YEAR START FOR THE DATA EXTRACT (YYYY)' 	ATTR = UNDERLINE C = BLUE
				+ 2 YEARSTRT 4 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES
		#26 '---------------------------------------------------------------------------------------------------------------------------'      	
		#28 @10 'ENTER Y TO DELETE THE INTERIM TABLES ON ORACLE, N TO LEAVE THEM ON ORACLE: ' 
						ATTR = UNDERLINE COLOR = BLUE
            		+ 2 DELX 1 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
            #30 @25 "FINALLY, MAKE SURE THAT EXCEL IS OPEN " C = RED ATTR= REV_VIDEO  
            #32 @20  "PRESS ENTER TO CONTINUE. THE JOB WILL TAKE A WHILE TO CONCLUDE" C = BLUE            
        ;
    %display compo ;

%MACRO SECOND_STEP ; 
OPTIONS MLOGIC MPRINT SYMBOLGEN ; 


%MACRO BASICS ; 
options mprint mlogic;
DATA MONTHS ; 
FORMAT STARTON ENDON MMDDYY10. RPT_DATE $9. ; 
  STARTON = INPUT("01&MONSTRT.&YEARSTRT",ANYDTDTE15. ) ; /* THE START DATE FROM THE MACRO */
  ENDON = INTNX('MONTH', STARTON,4)-1 ; /* THE END DATE 4 MONTH */  /*USER EDIT*/
  MONY = "'"||PUT(STARTON,YYMMDDN8.)||"'" ;  /* THIS IS THE START DATE FORMATTED */ 
  ASOF = "'"||PUT(TODAY(),YYMMDDN8.)||"'" ;  /* THIS IS THE AS OF DATE, WHICH IS THE DATE THE JOB WAS RUN */
  MMM1 = STRIP(PUT(STARTON,MONYY7.)) ; /*MMMYYYY FOR START DATE */
  MMM2 = STRIP(PUT(INTNX('MONTH', STARTON,4)-1,MONYY7.)) ; /*MMMYYYY FOR END DATE*/ /*USER EDIT*/
  RPT_DATE = TRIM(SUBSTR(ASOF,2,4)||'_'||SUBSTR(ASOF,6,4)) ; 
  TITLE = "FROM "||MMM1||" through "||MMM2 ; 
  CALL SYMPUT ('STARTCHCK',UPCASE(PUT(STARTON,WORDDATE15.))) ; 
  CALL SYMPUT ('ENDCHCK',UPCASE(PUT(ENDON,WORDDATE15.))) ; 
  CALL SYMPUT ('MONYY',COMPRESS(MMM1||'_'||MMM2,' ')) ; /* THIS IS FOR THE FILE NAME LATER */
  CALL SYMPUT ('FLDR',RPT_DATE) ; /* FOR THE FOLDER NAME */
  CALL SYMPUT ('DTRNG',TITLE) ; /* FOR THE REPORT TITLES */
  CALL SYMPUT ('ASOF', ASOF) ; /* THE AS OF DATE */
RUN ; 

  %IF &STARTCHCK = . %THEN %DO ; 
	  %window NODATE IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = RED
		   #20 @15 'OOPS! IT LOOKS LIKE THE DATE IS A PROBLEM, TRY ENTERING THE DATE AGAIN' C = WHITE 
		   ; 
	 %display NODATE ;

	%DISPLAY COMPO ; 

DATA MONTHS ; 
FORMAT STARTON ENDON MMDDYY10. RPT_DATE $9. ; 
  STARTON = INPUT("01&MONSTRT.&YEARSTRT",ANYDTDTE15. ) ; /* THE START DATE FROM THE MACRO */
  ENDON = INTNX('MONTH', STARTON,4)-1 ; /* THE END DATE 4 MONTH */ /*USER EDIT*/
  MONY = "'"||PUT(STARTON,YYMMDDN8.)||"'" ;  /* THIS IS THE START DATE FORMATTED */ 
  ASOF = "'"||PUT(TODAY(),YYMMDDN8.)||"'" ;  /* THIS IS THE AS OF DATE, WHICH IS THE DATE THE JOB WAS RUN */
  MMM1 = STRIP(PUT(STARTON,MONYY7.)) ; /*MMMYYYY FOR START DATE */
  MMM2 = STRIP(PUT(INTNX('MONTH', STARTON,4)-1,MONYY7.)) ; /*MMMYYYY FOR END DATE*/ /* USER EDIT*/
  RPT_DATE = TRIM(SUBSTR(ASOF,2,4)||'_'||SUBSTR(ASOF,6,4)) ; 
  TITLE = "FROM "||MMM1||" through "||MMM2 ; 
  CALL SYMPUT ('STARTCHCK',UPCASE(PUT(STARTON,WORDDATE15.))) ; 
  CALL SYMPUT ('ENDCHCK',UPCASE(PUT(ENDON,WORDDATE15.))) ; 
  CALL SYMPUT ('MONYY',COMPRESS(MMM1||'_'||MMM2,' ')) ; /* THIS IS FOR THE FILE NAME LATER */
  CALL SYMPUT ('FLDR',RPT_DATE) ; /* FOR THE FOLDER NAME */
  CALL SYMPUT ('DTRNG',TITLE) ; /* FOR THE REPORT TITLES */
  CALL SYMPUT ('ASOF', ASOF) ; /* THE AS OF DATE */
RUN ; 

%END ; 

  %IF &STARTCHCK > 1 %THEN %DO ; 
	  %window STARTDATE IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = GREEN 
		   #10 @15 "THE START DATE IS FOR THIS REPORT IS &STARTCHCK. " C = WHITE 
		   #14 @15 "THE END DATE IS FOR THIS REPORT IS &ENDCHCK. " C = YELLOW
		   #18 @15 "THE AS OF DATE IS FOR THIS REPORT IS &ASOF. " C = YELLOW
		   #22 @15 "THE TITLE FOR THIS REPORT IS &FLDR. " C = YELLOW
; 
	 %display STARTDATE ;
  %END ; 

%MEND BASICS ; 

%BASICS ; 

    /**************************** NOW PROCESS THE INDIVIDUAL REPORTS ON ORACLE **************************************/

/* READS THE MASTER FILE, AND PARSES THE JOBS BASED ON THE WORD, "CREATE." */
DATA OTHER  ; 
INFILE "Z:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\code\SAS_MASTER_COMPOSITE.txt" TRUNCOVER;

INPUT TEXT $170. @ ; 
IF INDEXW(TEXT,'CREATE TABLE')> 0 THEN CHECK = 'X'; /* IDENTIFY EACH TABLE START USING CREATE AS THE KEY*/
IF CHECK = 'X' THEN DO ; CHECKR +1 ; END ;   /* START TO COUNT AND ADD 1 AT EACH START POINT */
RUN ; 

/* COUNT HOW MANY JOBS THERE ARE */
PROC SQL ; 
SELECT COUNT(CHECK) INTO: CHECKS 
FROM OTHER ; 
QUIT ; 

/* CREATE A TEXT FILE FOR EACH JOB - THESE WILL BE IN SEQUENCE OF NUMBERS, E.G. STEP1.TXT */
%MACRO RUNIT (NOW) ; 

DATA _NULL_ ; 
FILE "Z:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\STEP&NOW..TXT" ; 
  PUT 'PROC SQL; ' ;
  PUT 'CONNECT TO ORACLE (PATH=DWP1RAC DBPROMPT=NO DEFER=NO USER=' "&UID." ' PASSWORD=' "&PWRD." ') ;' ; 
  PUT " EXECUTE (" ; 

DATA _NULL_ ; 
FILE "Z:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\STEP&NOW..TXT" MOD ; 
  SET OTHER ; 
  WHERE CHECKR = &NOW ; 
  IF TEXT = " " THEN DELETE ; 
		PUT @10 TEXT ; 

DATA _NULL_ ; 
FILE "Z:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\STEP&NOW..TXT" MOD ; 
PUT '         ) BY ORACLE; DISCONNECT FROM ORACLE; QUIT; ' ; 
RUN ; 

%MEND RUNIT ; 

/* CREATE THE TEXT FILE, AND RUN EACH ONE */
%MACRO RUNNING (NOW); 

%INCLUDE "Z:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\STEP&NOW..TXT" ; 

%MEND RUNNING ; 

DATA _NULL_ ; 
DO R = 1 TO &CHECKS. ; 
	CALL EXECUTE ('%RUNIT (NOW='||R||')') ; 
	CALL EXECUTE ('%RUNNING (NOW='||R||')') ; 
PUT "RAN JOB NUMBER " R " SUCCESSFULLY" ; 
END ; 
RUN ; 

%MEND SECOND_STEP ; 

%SECOND_STEP;

/********* NT removed this piece b/c couldn't get to run*************/

*%MACRO CONTROLLER2 ; 
/* CHECK TO SEE IF THE FIRST PROCESS COMPLETED, AND IF THE TABLE EXISTS*/
		*%IF %SYSFUNC(EXIST(NW.MCO_&QTR.V2_DOS_&MONYY)) = 1 %THEN %DO ; /* DO 1 */
		*	%PUT THE TABLE NW.MCO_&QTR.V2_DOS_&MONYY. EXISTS ; 

		*	%SECOND_STEP ; 

		*%END ;  /* END 1 */
*%MEND CONTROLLER2 ; 

*%CONTROLLER2 ; 
