
	/*THIS PROGRAM CREATES THE BASE DOS DATA WHICH IS USED TO REPORT ON THE DATA COMPLETENESS*/
    /* Need to update all instances of time range for ex: 12 or 16*/
/* NT: 7.2018 ADDED FIELD ACO */
%GLOBAL UID PWRD FLDR YEARSTRT MONSTRT QUARTER DTRNG DELX OBSCOUNT DSETS REVDATE MISSX NUMREXX  OBREX MONYY TIMETITLE; 

    %window compo IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = WHITE

            #08 @10 'THIS JOB WILL CREATE THE DISINCENTIVE REPORT FOR TIME PERIOD SPECIFIED' 
						ATTR = UNDERLINE C = GREEN
		#14 @10 'PLEASE ENTER YOUR ORACLE ID HERE: ' attr = underline C = BLUE
                 			+4 UID 20 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
		#16 @25 'AND YOUR ORACLE PASSWORD HERE: ' ATTR = UNDERLINE C = BLUE
                 			+4  PWRD 30 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
		#18 '---------------------------------------------------------------------------------------------------------------------------'
		#20 @10 'ENTER THE START MONTH FOR THE DATA EXTRACT, (IN THREE LETTERS E.G. MAY): ' 
						ATTR = UNDERLINE C = BLUE 
				+ 2 MONSTRT ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
            #22 @10 'ENTER THE YEAR TO START THE DATA EXTRACT, (YYYY)' 	ATTR = UNDERLINE C = BLUE
				+ 2 YEARSTRT 4 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 
		#26 '---------------------------------------------------------------------------------------------------------------------------'      	
		#28 @10 'ENTER Y TO DELETE THE INTERIM TABLES ON ORACLE, N TO LEAVE THEM ON ORACLE: ' 
						ATTR = UNDERLINE COLOR = BLUE
            		+ 2 DELX 1 ATTR=HIGHLIGHT C = BLACK REQUIRED = YES DISPLAY = YES 

            #30 @25 "FINALLY, MAKE SURE THAT EXCEL IS OPEN " C = RED ATTR= REV_VIDEO  
            #32 @20  "PRESS ENTER TO CONTINUE. THE JOB WILL TAKE A WHILE TO CONCLUDE" C = BLUE            
        ;
    %display compo ;

%MACRO FIRST_RUN ; 
OPTIONS MLOGIC MPRINT SYMBOLGEN ; 

%MACRO BASICS ; 
DATA MONTHS ; 
FORMAT STARTON ENDON MMDDYY10. RPT_DATE $9. ; 
  STARTON = INPUT("01&MONSTRT.&YEARSTRT",ANYDTDTE15. ) ; /* THE START DATE FROM THE MACRO */
  ENDON = INTNX('MONTH', STARTON,16)-1 ; /* THE END DATE 16 month period*/
  MONY = "'"||PUT(STARTON,YYMMDDN8.)||"'" ;  /* THIS IS THE START DATE FORMATTED */ 
  ASOF = "'"||PUT(TODAY(),YYMMDDN8.)||"'" ;  /* THIS IS THE AS OF DATE, WHICH IS THE DATE THE JOB WAS RUN */
  MMM1 = STRIP(PUT(STARTON,MONYY7.)) ; /*MMMYYYY FOR START DATE */
  MMM2 = STRIP(PUT(INTNX('MONTH', STARTON,16)-1,MONYY7.)) ; /*MMMYYYY FOR END DATE*/ /* 16 month period*/
  RPT_DATE = TRIM(SUBSTR(ASOF,2,4)||'_'||SUBSTR(ASOF,6,4)) ; 
  TITLE = "FROM "||MMM1||" through "||MMM2 ; 
  CALL SYMPUT ('STARTCHCK',UPCASE(PUT(STARTON,WORDDATE15.))) ; 
  CALL SYMPUT ('ENDCHCK',UPCASE(PUT(ENDON,WORDDATE15.))) ; 
  CALL SYMPUT ('MONYY',COMPRESS(MMM1||'_'||MMM2,' ')) ; /* THIS IS FOR THE FILE NAME LATER */
  CALL SYMPUT ('FLDR',RPT_DATE) ; /* FOR THE FOLDER NAME */
  CALL SYMPUT ('DTRNG',TITLE) ; /* FOR THE REPORT TITLES */
  CALL SYMPUT ('ASOF', ASOF) ; /* THE AS OF DATE */
RUN ; 

  %IF &STARTCHCK = . %THEN %DO ; 
	  %window NODATE IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = RED
		   #20 @15 'OOPS! IT LOOKS LIKE THE DATE IS A PROBLEM, TRY ENTERING THE DATE AGAIN' C = WHITE 
		   ; 
	 %display NODATE ;

	%DISPLAY COMPO ; 

DATA MONTHS ; 

FORMAT STARTON ENDON MMDDYY10. RPT_DATE $9. ; 
  STARTON = INPUT("01&MONSTRT.&YEARSTRT",ANYDTDTE15. ) ; /* THE START DATE FROM THE MACRO */
  ENDON = INTNX('MONTH', STARTON,16)-1 ; /* THE END DATE 16 month test period*/
  MONY = "'"||PUT(STARTON,YYMMDDN8.)||"'" ;  /* THIS IS THE START DATE FORMATTED */ 
  ASOF = "'"||PUT(TODAY(),YYMMDDN8.)||"'" ;  /* THIS IS THE AS OF DATE, WHICH IS THE DATE THE JOB WAS RUN */
  MMM1 = STRIP(PUT(STARTON,MONYY7.)) ; /*MMMYYYY FOR START DATE */
  MMM2 = STRIP(PUT(INTNX('MONTH', STARTON,16)-1,MONYY7.)) ; /*MMMYYYY FOR END DATE 16 month period*/
  RPT_DATE = TRIM(SUBSTR(ASOF,2,4)||'_'||SUBSTR(ASOF,6,4)) ; 
  TITLE = "FROM "||MMM1||" through "||MMM2 ; 
  CALL SYMPUT ('STARTCHCK',UPCASE(PUT(STARTON,WORDDATE15.))) ; 
  CALL SYMPUT ('ENDCHCK',UPCASE(PUT(ENDON,WORDDATE15.))) ; 
  CALL SYMPUT ('MONYY',COMPRESS(MMM1||'_'||MMM2,' ')) ; /* THIS IS FOR THE FILE NAME LATER */
  CALL SYMPUT ('FLDR',RPT_DATE) ; /* FOR THE FOLDER NAME */
  CALL SYMPUT ('DTRNG',TITLE) ; /* FOR THE REPORT TITLES */
  CALL SYMPUT ('ASOF', ASOF) ; /* THE AS OF DATE */
RUN ; 

%END ; 

  %IF &STARTCHCK > 1 %THEN %DO ; 
	  %window STARTDATE IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = GREEN 
		   #10 @15 "THE START DATE IS FOR THIS REPORT IS &STARTCHCK. " C = WHITE 
		   #14 @15 "THE END DATE IS FOR THIS REPORT IS &ENDCHCK. " C = YELLOW
		   #18 @15 "THE AS OF DATE IS FOR THIS REPORT IS &ASOF. " C = YELLOW
		   ; 
	 %display STARTDATE ;
  %END ; 

%MEND BASICS ; 

%BASICS ; 

%MACRO MAINFOLDER ( PATH ) ;
 DATA _NULL_ ;
   LENGTH PATH   $ 500
       FOLDER $ 100     ;

   PATH = SCAN( "&Path." , 1 , "\" ) ;
   DO _N_ = 2 TO COUNTC( "&Path." , "\" ) + 1 ;
       FOLDER = SCAN( "&Path." , _N_ , "\" ) ;
       RC = DCREATE( FOLDER , PATH ) ;
       PATH = CATS( PATH , "\" , FOLDER ) ;
       IF RC NE " " THEN PUT RC= ;
    END ;

 RUN ;

%MEND MAINFOLDER ;

/* PROCESS THE MACRO TO CREATE THE FOLDER(S) */
%MAINFOLDER(W:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.) ; 
%MAINFOLDER(W:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\DATASETS) ; 
%MAINFOLDER(W:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE) ; 

FILENAME OUTLOG "W:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\STEP1_SASLOG.TXT" ; 
PROC PRINTTO LOG=OUTLOG PRINT=OUTLOG NEW;

%LET TIMETITLE = &DTRNG. ; 

/****************************************************************************************************************/

%MACRO OPENER (MON) ; 

FILENAME MOPS "W:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\SQL CODE FOR DOS &MON..TXT" ; 

DATA _NULL_ ; 
  FILE MOPS ; 
  PUT 'PROC SQL; ' ;
  PUT 'CONNECT TO ORACLE (PATH=DWP1RAC DBPROMPT=NO DEFER=NO USER=' "&UID." ' PASSWORD=' "&PWRD." ') ;' ; 
  PUT "    EXECUTE (CREATE TABLE MCO_MBHP_DOS_&MON.  " ; 
RUN ; 

%MEND OPENER ; 


%MACRO MIDDER ; 
DATA _NULL_ ; 
  FILE MOPS MOD; 
PUT @ 10 "NOLOGGING " ;
PUT @ 10 "COMPRESS " ;
PUT @ 10 "AS " ;

PUT @ 10 "SELECT " ;
PUT @ 10 "ENC.CDE_ENC_MCO, " ;
PUT @ 10 "ENC.CDE_ENC_ACO, ";
PUT @ 10 "CASE WHEN ENC.CDE_ENC_ACO in('#','+','-') THEN 'NA' ELSE ENC.CDE_ENC_ACO END AS ACO, ";
PUT @ 10 "MEM.ID_MEDICAID, " ;
PUT @ 10 "ENCATT.CDE_ENC_REC_IND, ";
PUT @ 10 "ENCATT.DSC_ENC_REC_IND, ";
PUT @ 10 "ENC.DOS_FROM_DT AS DOS_FROM, " ;
PUT @ 10 "ENC.DOS_TO_DT AS DOS_THRU, " ;
PUT @ 10 "ENC.REMIT_FROM_DT AS PAID_DT, ";
PUT @ 10 "ENC.ADMIT_DT, ";
PUT @ 10 "ENC.DISCHARGE_DT, ";
PUT @ 10 "ENC.DATE_SCRIPT_WRITTEN, ";
PUT @ 10 "ENC.QTY_REFILL, ";
PUT @ 10 "ENC.QTY_UNITS_BILLED, ";
PUT @ 10 "ENC.RX_NUMBER, ";
PUT @ 10 "ENC.AMT_NDC_PROFEE, ";
PUT @ 10 "ENC.ENCSRGGRP_SEQ, ";
PUT @ 10 "DIAGGRP.CDE_DIAG_ADMIT, ";
PUT @ 10 "DIAGGRP.DSC_DIAG_ADMIT, ";
PUT @ 10 "CSA.CDE_PATIENT_STATUS, ";
PUT @ 10 "CSA.DSC_PATIENT_STATUS, ";
PUT @ 10 "DIAGGRP.CDE_DIAG_1 AS PRIMARY_DIAG, ";
PUT @ 10 "DIAGGRP.DSC_DIAG_1 AS PRIMARY_DIAG_DESC, "; 
PUT @ 10 "DIAGGRP.CDE_ICD_VERSION, ";
PUT @ 10 "DIAGGRP.DIAGRP_SEQ, ";
PUT @ 10 "CSA.CDE_ADMIT_TYPE, ";
PUT @ 10 "CSA.DSC_ADMIT_TYPE, ";
PUT @ 10 "CSA.CDE_ADMIT_SOURCE, ";
PUT @ 10 "NCF.CDE_ENC_PROC AS PROC_CODE_ENC, ";
PUT @ 10 "NCF.DSC_ENC_PROC AS PROC_CODE_ENC_DESC, "; 
PUT @ 10 "PROC.CDE_PROC AS PROC_CODE, ";
PUT @ 10 "PROC.DSC_PROC AS PROC_CODE_DESC, "; 
PUT @ 10 "MFR.CDE_PROC_MOD AS PROC_MODIFIER1,";
PUT @ 10 "MFR.DSC_PROC_MOD AS PROC_MODIFIER1_DESC,"; 
PUT @ 10 "MFR.CDE_PROC_MOD_2 AS PROC_MODIFIER2,";
PUT @ 10 "MFR.DSC_PROC_MOD_2 AS PROC_MODIFIER2_DESC,";
PUT @ 10 "MFR.CDE_PROC_MOD_3 AS PROC_MODIFIER3,";
PUT @ 10 "MFR.DSC_PROC_MOD_3 AS PROC_MODIFIER3_DESC,";
PUT @ 10 "MFR.CDE_PROC_MOD_4 AS PROC_MODIFIER4,";
PUT @ 10 "MFR.DSC_PROC_MOD_4 AS PROC_MODIFIER4_DESC,";
PUT @ 10 "NCF.CDE_ENC_PROC_TYPE, ";
PUT @ 10 "NCF.DSC_ENC_PROC_TYPE, ";
PUT @ 10 "CSA.CDE_REVENUE, ";
PUT @ 10 "CSA.DSC_REVENUE, ";
PUT @ 10 "CSA.CDE_PLACE_OF_SERVICE, ";
PUT @ 10 "CSA.DSC_PLACE_OF_SERVICE, ";
PUT @ 10 "SUBSTR(CSA.CDE_PLACE_OF_SERVICE,2,2) AS PLACE_OF_SERVICE, ";
PUT @ 10 "SUBSTR(CSA.CDE_PLACE_OF_SERVICE,1,1) AS PLACE_OF_SERVICE_TYPE, ";
PUT @ 10 "CSA.CDE_PLACE_OF_SERVICE_ENC, ";
PUT @ 10 "CSA.CDE_TYPE_OF_BILL, ";
PUT @ 10 "CSA.CDE_TYPE_OF_BILL_ENC, ";
PUT @ 10 "CSA.CDE_BILL_FREQ, ";
PUT @ 10 "SVC_PROV.ID_PROVIDER AS SERV_PROV_ID, " ;
PUT @ 10 "SVC_PROV.ENC_PROV_ID AS ENC_SERV_PROV_ID, " ;
PUT @ 10 "SVC_PROV.DSC_ENC_PROV_ID_TYPE AS SERV_PROV_ID_TYPE, " ;
PUT @ 10 "SVC_PROV.ID_NPI AS SERV_NPI, ";
PUT @ 10 "SVC_PROV.CDE_ENC_PROV_TYPE AS ENC_SERV_PROV_TYPE, ";
PUT @ 10 "SVC_PROV.CDE_ENC_PROV_ID_LOC AS SERV_PROV_ID_LOC_CODE, ";
PUT @ 10 "NCF.CDE_ENC_PROV_SPEC AS SERV_PROV_SPECIALTY," ;
PUT @ 10 "PROV.ID_PROVIDER AS BILL_PROV_ID, " ;
PUT @ 10 "PROV.ENC_PROV_ID AS ENC_BILL_PROV_ID, " ;
PUT @ 10 "PROV.DSC_ENC_PROV_ID_TYPE AS BILL_PROV_ID_TYPE, " ;
PUT @ 10 "PROV.CDE_ENC_PROV_ID_LOC AS BILL_PROV_ID_LOC_CODE, ";
PUT @ 10 "PROV.ID_NPI AS BILL_NPI, ";
PUT @ 10 "PRS_PROV.ID_PROVIDER AS PRES_PROV_ID, " ;
PUT @ 10 "PRS_PROV.ENC_PROV_ID AS ENC_PRES_PROV_ID, " ;
PUT @ 10 "PRS_PROV.DSC_ENC_PROV_ID_TYPE AS PRES_PROV_ID_TYPE, " ;
PUT @ 10 "PRS_PROV.CDE_ENC_PROV_ID_LOC AS PRS_PROV_ID_LOC_CODE, ";
PUT @ 10 "DRG.CDE_DRUG_CLASS, ";
PUT @ 10 "DRG.CDE_NDC, ";
PUT @ 10 "ENC.CDE_CLM_TYPE AS CLAIM_TYPE, " ;
PUT @ 10 "ENC.ENC_CLAIM_NO, " ;
PUT @ 10 "ENC.ENC_CLAIM_SUFFIX, " ;
PUT @ 10 "ENC.AMT_PAID, " ; 
PUT @ 10 "ENC.AMT_BILLED, ";
PUT @ 10 "ENC.AMT_ALLOWED, "; 
PUT @ 10 "ENC.CDE_CLM_DISPOSITION, ";
PUT @ 10 "ENC.AMT_TPL, ";
PUT @ 10 "ENC.AMT_COPAY, ";
PUT @ 10 "ENC.AMT_COINSURANCE, ";
PUT @ 10 "ENC.NUM_LOGICAL_CLAIM, ";
PUT @ 10 "ENCATT.CDE_ENC_DISP_AS_WRTN, ";
PUT @ 10 "ENCATT.DSC_ENC_DISP_AS_WRTN, ";
PUT @ 10 "ENCATT.CDE_ENC_CLAIM_CAT, ";
PUT @ 10 "ENCATT.DSC_ENC_CLAIM_CAT, ";
PUT @ 10 "ENCATT.CDE_ENC_SVC_CAT, ";
PUT @ 10 "ENCATT.DSC_ENC_SVC_CAT, ";
PUT @ 10 "ENCATT.IND_ENC_COMPOUND ";
PUT @ 10 "FROM NW_ENCOUNTER_HIST ENC " ;
PUT @ 10 "LEFT OUTER JOIN NW.NW_ENC_ATTRIBUTE ENCATT ON ENC.ATTRENC_SEQ = ENCATT.ATTRENC_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_MEMBER MEM ON ENC.MEM_SEQ = MEM.MEM_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_DIAGNOSIS_GROUP DIAGGRP ON ENC.DIAGRP_SEQ = DIAGGRP.DIAGRP_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_CLAIM_SERVICE_ATTRIBUTE CSA ON ENC.ATTRSRV_SEQ = CSA.ATTRSRV_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_PROCEDURE PROC ON ENC.PROC_SEQ = PROC.PROC_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_PROCEDURE_MFR_GROUP MFR ON ENC.PROCMFRGRP_SEQ= MFR.PROCMFRGRP_SEQ ";
PUT @ 10 "LEFT OUTER JOIN NW_DRUG DRG ON ENC.DRUG_SEQ = DRG.DRUG_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_ENC_PROVIDER PROV ON ENC.BILL_ENCPRV_SEQ = PROV.ENCPRV_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_ENC_PROVIDER SVC_PROV ON ENC.SRV_ENCPRV_SEQ = SVC_PROV.ENCPRV_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_ENC_PROVIDER REF_PROV ON ENC.REF_ENCPRV_SEQ = REF_PROV.ENCPRV_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_ENC_PROVIDER PRS_PROV ON ENC.PRS_ENCPRV_SEQ = PRS_PROV.ENCPRV_SEQ " ;
PUT @ 10 "LEFT OUTER JOIN NW_ENC_NONCONF_ATTRIBUTE NCF ON NCF.ATTRENC_NC_SEQ = ENC.ATTRENC_NC_SEQ " ;

PUT " " ; 
RUN ; 
%MEND MIDDER ; 

%MACRO ENDER (MONS,ASOFDT);  
DATA _NULL_ ; 
  FILE MOPS MOD; 
PUT @ 10 "WHERE  ENC.DOS_FROM_DT BETWEEN TO_DATE(&MONS.,'YYYYMMDD') " ;
PUT @ 10 "        AND ((TO_DATE(&MONS., 'YYYYMMDD') + INTERVAL '16' MONTH ) -1)" ; 
PUT @ 10 "AND  ENC.REMIT_THRU_DT = TO_DATE('99991231','YYYYMMDD')   " ; 
PUT @ 10 "AND TO_DATE(&ASOFDT.,'YYYYMMDD') BETWEEN ENC.WH_FROM_DT AND ENC.WH_THRU_DT   " ; 
PUT @ 10 "AND ENC.CDE_CLM_DISPOSITION <> 'V' ";
PUT @ 10 "AND ENC.IND_OFFSET = 'N' ";
PUT @ 10 "AND ENC.CDE_ENC_MCO IN('BMC','CHA','FLN','NHP','HNE','MBH')  " ; 
PUT '       ) BY ORACLE; DISCONNECT FROM ORACLE; QUIT; ' ; 
RUN ; 
%MEND ENDER ; 

%MACRO RUNNER (MON) ; 
 
%INCLUDE "W:\APPLICATION ANALYSIS\MCO and MBHP Evaluation Scorecard\&MONYY.\MONTHLY DETAILS\&FLDR.\SASCODE\SQL CODE FOR DOS &MON..TXT" ; 

%MEND RUNNER ; 

/* NOW PROCESS THE DATA INTO ONE TEXT FILE AND RUN THAT FILE TO EXECUTE THE SQL PROCESS */
DATA _NULL_ ; 
  SET MONTHS ; 
  CALL EXECUTE ('%OPENER (MON='||COMPRESS(MMM1||'_'||MMM2,' ')||')') ;
  CALL EXECUTE ('%MIDDER') ; 
  CALL EXECUTE ('%ENDER  (MONS='||MONY||',ASOFDT='||ASOF||')') ; 
  CALL EXECUTE ('%RUNNER  (MON='||COMPRESS(MMM1||'_'||MMM2,' ')||')') ; /* RUN THE JOB TO CREATE THE DATASET */ 
RUN; 

PROC PRINTTO ; RUN ; 

/* ASSIGN THE LIBNAME FOR THE DATA WAREHOUSE */
LIBNAME NW ORACLE PATH=DWP1RAC SCHEMA=&UID DBPROMPT=NO DEFER=NO USER=&UID PASSWORD=&PWRD;

/* CHECK TO SEE IF THE FIRST PROCESS COMPLETED, AND IF THE TABLE EXISTS*/
		%IF %SYSFUNC(EXIST(NW.MCO_MBHP_DOS_&MONYY)) = 1 %THEN %DO ; /* DO 1 */
			%PUT THE TABLE NW.MCO_MBHP_DOS_&MONYY. EXISTS ; 

			PROC SQL ; 
			SELECT COUNT(*) INTO :OBREX 
			FROM NW.MCO_MBHP_DOS_&MONYY. ; 
			QUIT ; 
		%END ;  /* END 1 */

%PUT THE NUMBER OF RECORDS IN THE TABLE IS &OBREX. ; 

%IF %SYSFUNC(EXIST(NW.MCO_MBHP_DOS_&MONYY.)) < 1 %THEN %GOTO NOWT ; 
%IF &OBREX < 1 %THEN %GOTO NOWT ; 

%NOWT: 

%IF &OBREX < 1 %THEN %DO ; 

    DATA NOSPACE ; 
      INFILE OUTLOG TRUNCOVER ; 
	INPUT @01 TEXT $6. @; 
	  IF TEXT = 'ERROR:' THEN INPUT @ 01 REASON $81. /
										@ 08 REASON2 $18. ;
        COMBO = REASON||REASON2 ; 
        IF TEXT = 'ERROR:' THEN CALL SYMPUT('ERRX',COMBO) ; 
        IF TEXT = 'ERROR:' ; 
   RUN ; 

			PROC SQL ; 
			SELECT COUNT(*) INTO :NOFILEREX 
			FROM NOSPACE  ; 
			QUIT ; 

%IF &NOFILEREX > 0 %THEN %DO ; 

%window NOCLMS IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = BLACK

            #14 @20 'NOTE: THE CLAIMS DATA WAS NOT CREATED FOR THE FOLLOWING REASON:' attr = underline COLOR = WHITE 
            #18 @05 "&ERRX." attr = underline COLOR = PINK 
            #28 @20  "PRESS ENTER TO CONCLUDE " COLOR = WHITE 
        ;
    %display NOCLMS ;

%END ; 

%IF &NOFILEREX = 0 %THEN %DO ; 

%window NOCLMS IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = BLACK

            #14 @20 'NOTE: THE CLAIMS DATA WAS NOT CREATED, PLEASE CHECK THE LOG TO SEE WHY' attr = underline COLOR = WHITE 
            #28 @20  "PRESS ENTER TO CONCLUDE " COLOR = WHITE 
        ;
    %display NOCLMS ;

%END ; 

%END ; 

%END ; 

%IF &OBREX > 0 %THEN %DO ; 

    %window YESCLMS IROW = 0 ROWS = 150 ICOLUMN = 0 COLUMNS = 125 COLOR = GREEN 

            #14 @20 'NOTE: THE CLAIMS DATA WAS CREATED' ATTR = UNDERLINE COLOR = WHITE 
            #18 @20 "AND HAS A TOTAL OF &OBREX. RECORDS" ATTR = UNDERLINE COLOR = WHITE 
            #32 @25  "PRESS ENTER TO CONCLUDE THIS PHASE" COLOR = WHITE 
        ;
    %display YESCLMS ;
%END ; 


%MEND FIRST_RUN ; 

%FIRST_RUN ; 
