
/*NEED TO DEVELOP A QUICK QA OF FINAL DATA AND COMPARISON TO PREVIOUS RUN*/
/*ALSO NEED TO SPOT CHECK A FEW FIELDS FROM EACH MCO IN THE FINAL SPREADSHEET AGAINST THE DATA TABLE GENERATED IN SAS*/

/******************************************************************************
 PROGRAM:     REPORT_COMPARE.SQL
 RE:          QUICK COMPARISON OF LAST RUN OF THIS DOS QUARTERLY REPORT
              AGAINST THE REFRESHED DATA
 DATE:        8.15.2018
 NOTE:        THERE ARE VERY MINIMAL DIFFERENCES ACROSS ALL MEASURES. 
              NOTHING SIGNIFICANT TO LOOK INTO
              JUL-SEP 2017 DOS: 6.14.18 VS. 8.13.18 RUNS
 ******************************************************************************/


select 
CDE_ENC_MCO,
PCT_ID_MEDICAID_DIFF, 
PCT_DOS_FROM_DIFF, 
PCT_DOS_THRU_DIFF, 
PCT_SERV_PROV_ID_DIFF, 
PCT_SERV_PROV_ID_TYP_DIFF, 
PCT_SERV_PROV_TYP_DIFF, 
PCT_SERV_PROV_SPEC_DIFF, 
PCT_BILL_PROV_SPEC_DIFF,
PCT_BILL_PROV_ID_DIFF, 
PCT_BILL_PROV_ID_TYP_DIFF, 
PCT_PRESCRIBE_PROV_ID_DIFF, 
PCT_PRES_PROV_ID_TYP_DIFF, 
PCT_PRIMARY_DIAG_DIFF, 
PCT_ICD_VERSION_DIFF, 
PCT_PROC_CODE_O_DIFF, 
PCT_PROC_CODE_M_DIFF, 
PCT_PROC_MOD_DME_DIFF, 
PCT_PROC_MOD_LABXRAY_DIFF, 
PCT_PROC_MOD_SURGERYM_DIFF, 
PCT_QTY_UNIT_BILL_DIFF, 
PCT_MEDICARE_CODE_DIFF, 
PCT_AMT_GROSSPAY_DIFF, 
PCT_AMT_PAYMCARE_DIFF, 
PCT_SVC_CAT_DIFF, 
PCT_PAT_PAYAMT_DIFF, 
PCT_SCRIPT_WRITTEN_DIFF, 
PCT_REFILL_DIFF, 
PCT_DISPENSE_DIFF, 
PCT_SCRIPT_DIFF, 
PCT_FEE_DIFF, 
PCT_NDC_DIFF, 
PCT_CLAIMCAT_DIFF, 
PCT_RECIND_DIFF, 
PCT_AMTBILL_DIFF, 
PCT_PAY_DIFF, 
PCT_AMTALLOW_DIFF, 
PCT_ADMITDT_DIFF, 
PCT_DISCHARGEDT_DIFF, 
PCT_DIAG_ADMIT_DIFF,
PCT_PATIENT_STATUS_DIFF,
PCT_ADMIT_TYPE_DIFF,
PCT_ADMIT_SOURCE_DIFF,
PCT_REV_CODE_DIFF,
PCT_POS_CODE_DIFF, 
PCT_POS_TYPE_DIFF
from
(select q3.cde_enc_mco, 
q3.PCT_ID_MEDICAID - q3old.PCT_ID_MEDICAID as pct_id_medicaid_diff,
q3.PCT_DOS_FROM - q3old.PCT_DOS_FROM as pct_dos_from_diff,
q3.PCT_DOS_THRU - q3old.PCT_DOS_THRU as pct_dos_thru_diff,
q3.PCT_SERV_PROV_ID - q3old.PCT_SERV_PROV_ID as PCT_SERV_PROV_ID_diff, 
q3.PCT_SERV_PROV_ID_TYP -q3old.PCT_SERV_PROV_ID_TYP AS PCT_SERV_PROV_ID_TYP_diff,
q3.PCT_SERV_PROV_TYP - q3old.PCT_SERV_PROV_TYP AS PCT_SERV_PROV_TYP_diff,
q3.PCT_SERV_PROV_SPEC - q3old.PCT_SERV_PROV_SPEC AS PCT_SERV_PROV_SPEC_diff, 
q3.PCT_BILL_PROV_SPEC - q3old.PCT_BILL_PROV_SPEC AS PCT_BILL_PROV_SPEC_diff, 
q3.PCT_BILL_PROV_ID - q3old.PCT_BILL_PROV_ID AS PCT_BILL_PROV_ID_diff, 
q3.PCT_BILL_PROV_ID_TYP - q3old.PCT_BILL_PROV_ID_TYP AS PCT_BILL_PROV_ID_TYP_diff, 
q3.PCT_PRESCRIBE_PROV_ID - q3old.PCT_PRESCRIBE_PROV_ID AS PCT_PRESCRIBE_PROV_ID_diff, 
q3.PCT_PRES_PROV_ID_TYP - q3old.PCT_PRES_PROV_ID_TYP AS PCT_PRES_PROV_ID_TYP_diff, 
q3.PCT_PRIMARY_DIAG - q3old.PCT_PRIMARY_DIAG AS PCT_PRIMARY_DIAG_diff, 
q3.PCT_ICD_VERSION - q3old.PCT_ICD_VERSION AS PCT_ICD_VERSION_diff, 
q3.PCT_PROC_CODE_O - q3old.PCT_PROC_CODE_O AS PCT_PROC_CODE_O_diff, 
q3.PCT_PROC_CODE_M - q3old.PCT_PROC_CODE_M AS PCT_PROC_CODE_M_diff, 
q3.PCT_PROC_MOD_DME -q3old.PCT_PROC_MOD_DME AS PCT_PROC_MOD_DME_diff, 
q3.PCT_PROC_MOD_LABXRAY - q3old.PCT_PROC_MOD_LABXRAY AS PCT_PROC_MOD_LABXRAY_diff, 
q3.PCT_PROC_MOD_SURGERYM - q3old.PCT_PROC_MOD_SURGERYM AS PCT_PROC_MOD_SURGERYM_diff, 
q3.PCT_QTY_UNIT_BILL - q3old.PCT_QTY_UNIT_BILL AS PCT_QTY_UNIT_BILL_diff, 
q3.PCT_MEDICARE_CODE - q3old.PCT_MEDICARE_CODE AS PCT_MEDICARE_CODE_diff, 
q3.PCT_AMT_GROSSPAY - q3old.PCT_AMT_GROSSPAY AS PCT_AMT_GROSSPAY_diff, 
q3.PCT_AMT_PAYMCARE - q3old.PCT_AMT_PAYMCARE AS PCT_AMT_PAYMCARE_diff, 
q3.PCT_SVC_CAT - q3old.PCT_SVC_CAT AS PCT_SVC_CAT_diff, 
q3.PCT_PAT_PAYAMT - q3old.PCT_PAT_PAYAMT AS PCT_PAT_PAYAMT_diff, 
q3.PCT_SCRIPT_WRITTEN - q3old.PCT_SCRIPT_WRITTEN AS PCT_SCRIPT_WRITTEN_diff, 
Q3.PCT_REFILL - q3old.PCT_REFILL AS PCT_REFILL_diff, 
Q3.PCT_DISPENSE- q3old.PCT_DISPENSE AS PCT_DISPENSE_diff, 
Q3.PCT_SCRIPT - q3old.PCT_SCRIPT AS PCT_SCRIPT_diff, 
Q3.PCT_FEE - q3old.PCT_FEE AS PCT_FEE_diff, 
Q3.PCT_NDC - q3old.PCT_NDC AS PCT_NDC_diff, 
Q3.PCT_CLAIMCAT - q3old.PCT_CLAIMCAT AS PCT_CLAIMCAT_diff, 
Q3.PCT_RECIND - q3old.PCT_RECIND AS PCT_RECIND_diff, 
Q3.PCT_AMTBILL - q3old.PCT_AMTBILL AS PCT_AMTBILL_diff, 
Q3.PCT_AMTPAY - q3old.PCT_AMTPAY AS PCT_PAY_diff, 
Q3.PCT_AMTALLOW - q3old.PCT_AMTALLOW AS PCT_AMTALLOW_diff,
Q3.PCT_ADMITDT - q3old.PCT_ADMITDT AS PCT_ADMITDT_diff, 
Q3.PCT_DISCHARGEDT - q3old.PCT_DISCHARGEDT AS PCT_DISCHARGEDT_diff, 
Q3.PCT_DIAG_ADMIT - q3old.PCT_DIAG_ADMIT AS PCT_DIAG_ADMIT_diff, 
Q3.PCT_PATIENT_STATUS - q3old.PCT_PATIENT_STATUS AS PCT_PATIENT_STATUS_diff, 
Q3.PCT_ADMIT_TYPE - q3old.PCT_ADMIT_TYPE AS PCT_ADMIT_TYPE_diff, 
Q3.PCT_ADMIT_SOURCE - q3old.PCT_ADMIT_SOURCE AS PCT_ADMIT_SOURCE_diff, 
Q3.PCT_REV_CODE - q3old.PCT_REV_CODE AS PCT_REV_CODE_diff, 
Q3.PCT_POS_CODE - q3old.PCT_POS_CODE AS PCT_POS_CODE_diff, 
Q3.PCT_POS_TYPE - q3old.PCT_POS_TYPE AS PCT_POS_TYPE_diff
from sco_percents_q3 q3
inner join sco_percents_q3_20180608 q3old
on q3.cde_enc_mco=q3old.cde_enc_mco
)WHERE 